<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
	<Version>2.0.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Yojigen Point Security</Title>
    <Authors>Yojigen Point</Authors>
    <Company>Yojigen Point</Company>
    <Description>A modern, professional security library for .NET, providing robust and easy-to-use services for AES-256 encryption and BCrypt password hashing. Designed for dependency injection and testability.</Description>
    <Copyright>Copyright {c} Yojigen Point 2025</Copyright>
    <PackageProjectUrl>https://github.com/yojigenpoint/YojigenPoint.Security</PackageProjectUrl>
    <PackageIcon>yp_logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/yojigenpoint/YojigenPoint.Security.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>security crypto encryption aes bcrypt password hashing helper extensions dotnet csharp</PackageTags>
    <PackageReleaseNotes>Add support for .NET 10.</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Yojigen\Downloads\yp_logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

</Project>
